name: dart_cas
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  requests:
    git:
      url: https://github.com/sehnryr/requests.git
      ref: master
  tuple: ^2.0.0
  xpath_selector: ^2.2.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
